import '/postnl_lrvdlinden_static/postnl-card.js?v=1.0.1';

const BASE='/postnl_lrvdlinden_static';
const ICON=`${BASE}/icon.svg`;
const VAN_STATIC=`${BASE}/van-1.svg`;
const VAN=`${BASE}/postnl-van.gif`;
const PACKAGE=`${BASE}/package.svg`;
const text=v=>String(v??'').trim();
const langOf=h=>String(h?.language||navigator.language||'en').toLowerCase().split('-')[0]==='nl'?'nl':'en';
const findEntity=(h,role,configured)=>configured&&h.states[configured]?configured:Object.keys(h.states).find(id=>h.states[id]?.attributes?.postnl_role===role)||null;
const zoned=raw=>/(?:Z|[+-]\d{2}:?\d{2})$/i.test(raw);
function parts(value,tz){const raw=text(value);if(!raw)return null;let m=raw.match(/^(\d{4})-(\d{2})-(\d{2})[T\s](\d{2}):(\d{2})/);if(m&&!zoned(raw))return{date:`${m[1]}-${m[2]}-${m[3]}`,mins:+m[4]*60 + +m[5],time:`${m[4]}:${m[5]}`};const d=new Date(raw);if(Number.isNaN(d.getTime()))return null;try{const p=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d),g=t=>p.find(x=>x.type===t)?.value||'';return{date:`${g('year')}-${g('month')}-${g('day')}`,mins:+g('hour')*60 + +g('minute'),time:`${g('hour')}:${g('minute')}`}}catch(_){return null}}
function nowParts(tz){const d=new Date();try{const p=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(d),g=t=>p.find(x=>x.type===t)?.value||'',hh=+g('hour'),mm=+g('minute'),ss=+g('second');return{date:`${g('year')}-${g('month')}-${g('day')}`,mins:hh*60+mm,secs:hh*3600+mm*60+ss}}catch(_){return{date:'',mins:0,secs:0}}}
function addDay(key,n){const[y,m,d]=key.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n,12));return x.toISOString().slice(0,10)}
function dmy(k){if(!k)return'';const[y,m,d]=k.split('-');return`${d}-${m}-${y}`}
function fmt(t,vars){return Object.entries(vars).reduce((s,[k,v])=>s.replace(`{${k}}`,v),t)}
function hhmm(total){const mins=((Math.round(total)%1440)+1440)%1440;return`${String(Math.floor(mins/60)).padStart(2,'0')}:${String(mins%60).padStart(2,'0')}`}
const CSS=`:host{display:block;height:360px}*{box-sizing:border-box}.card{--orange:#FB6200;--primary:#232323;--secondary:#747378;--muted:#97969b;--card:#f4f4f5;--header:#fafafa;--border:#dedee0;--panel:#fff;--line:#777b9c;display:grid;grid-template-rows:52px minmax(0,1fr);width:100%;height:100%;overflow:hidden;border-radius:17px;background:var(--card);color:var(--primary);font:14px/1.28 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{display:flex;align-items:center;padding:0 18px;border-bottom:1px solid var(--border);background:var(--header)}.app-icon{display:block;width:36px;height:36px;object-fit:contain}h1{margin:0 0 0 auto;color:#77767b;font-size:18px;font-weight:600;white-space:nowrap}.content{min-width:0;min-height:0;padding:10px 12px;overflow:hidden}.package{height:100%;min-height:0;overflow:hidden;border-radius:12px;background:var(--panel);padding:12px 12px 10px;display:flex;flex-direction:column}.package-top{display:flex;align-items:center;gap:9px;min-height:28px}.mini-logo{width:38px;height:38px;object-fit:contain;flex:0 0 auto}.sender{font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:1}.status{color:var(--secondary);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:40%}.headline{font-size:13px;font-weight:650;margin:9px 0 1px;min-height:17px}.tracking{color:var(--muted);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-height:13px}.vanwrap{flex:1;min-height:82px;display:grid;place-items:center;padding:4px 0}.van{display:block;max-width:260px;max-height:145px;object-fit:contain}.van.animated-van{width:240px;height:auto;max-width:100%;max-height:none;object-fit:contain}.timeline{position:relative;height:58px;margin-top:0}.track{position:absolute;left:0;right:0;top:20px;height:3px;background:var(--line)}.elapsed{position:absolute;left:0;top:20px;height:3px;background:var(--orange);width:0}.dot{position:absolute;top:12px;width:18px;height:18px;margin-left:-9px;border:4px solid var(--orange);border-radius:50%;background:var(--panel);left:0}.actual-start,.actual-end{position:absolute;top:11px;width:3px;height:21px;background:#cfcfd5;border-radius:2px}.times{position:absolute;left:0;right:0;top:33px;display:grid;grid-template-columns:1fr 1fr 1fr;color:var(--muted);font-size:10px}.times span:nth-child(2){text-align:center}.times span:nth-child(3){text-align:right}.hidden{display:none!important}.state{display:grid;place-items:center;height:100%;padding:16px;text-align:center;color:var(--primary)}.state-inner{display:grid;place-items:center;gap:12px}.state .van{width:min(88%,290px);max-height:170px}.state p{margin:0;font-size:17px;font-weight:700}@media(prefers-color-scheme:dark){.card{--primary:#f4f4f5;--secondary:#c4c3c7;--muted:#aaa9ad;--card:#202022;--header:#29292b;--border:#424244;--panel:#343436;--line:#71748e}h1{color:#aaa9ad}.dot{background:var(--panel)}.state{color:#aaa9ad}}`;
const labels={nl:{title:'Mijn Bezorging',empty:'Er is geen pakket onderweg',today:'Vandaag tussen {from} en {to}',tomorrow:'Morgen tussen {from} en {to}',date:'{date} tussen {from} en {to}',tracking:'Tracking'},en:{title:'My Delivery',empty:'There is currently no parcel on the way',today:'Today between {from} and {to}',tomorrow:'Tomorrow between {from} and {to}',date:'{date} between {from} and {to}',tracking:'Tracking'}};
const Delivery=customElements.get('postnl-delivery-card');
if(Delivery){
 Delivery.prototype.render=function(){const h=this._hass;if(!h)return;const id=findEntity(h,'packages',this._config?.entity),s=id?h.states[id]:null,a=s?.attributes||{},p=a.active_package,l=labels[langOf(h)],tz=a.time_zone||h.config?.time_zone||'Europe/Amsterdam';this._parcel=p;this._timeZone=tz;if(!p){this.shadowRoot.innerHTML=`<style>${CSS}</style><main class="card"><header><img class="app-icon" src="${ICON}" alt="PostNL"><h1>${l.title}</h1></header><section class="content"><div class="state"><div class="state-inner"><img class="van" src="${VAN_STATIC}" alt="PostNL"><p>${l.empty}</p></div></div></section></main>`;return}const from=parts(p.delivery_window_from,tz),to=parts(p.delivery_window_to,tz),n=nowParts(tz),date=from?.date||parts(p.delivery_date,tz)?.date||'';let headline=text(p.status),fromTime=from?.time||'',toTime=to?.time||'';if(fromTime&&toTime){const template=date===n.date?l.today:date===addDay(n.date,1)?l.tomorrow:l.date;headline=fmt(template,{from:fromTime,to:toTime,date:dmy(date)})}const sender=text(p.sender||p.title||p.source_display_name||'PostNL'),tracking=text(p.tracking),status=text(p.status);this.shadowRoot.innerHTML=`<style>${CSS}</style><main class="card"><header><img class="app-icon" src="${ICON}" alt="PostNL"><h1>${l.title}</h1></header><section class="content"><section class="package"><div class="package-top"><img class="mini-logo" src="${PACKAGE}" alt="Package"><div class="sender">${sender}</div><div class="status">${status}</div></div><div class="headline">${headline}</div><div class="tracking">${tracking?`${l.tracking}: ${tracking}`:''}</div><div class="vanwrap"><img class="van animated-van" src="${VAN}" alt="PostNL"></div><div class="timeline ${from&&to?'':'hidden'}"><div class="track"></div><div class="elapsed"></div><div class="dot"></div><i class="actual-start"></i><i class="actual-end"></i><div class="times"><span></span><span></span><span></span></div></div></section></section></main>`;this.updateProgress()};
 Delivery.prototype.updateProgress=function(){const p=this._parcel,tz=this._timeZone;if(!p||!this.shadowRoot)return;const a=parts(p.delivery_window_from,tz),b=parts(p.delivery_window_to,tz),n=nowParts(tz);if(!a||!b)return;const displayStart=a.mins-60,displayEnd=b.mins+60,startSec=displayStart*60,endSec=displayEnd*60;let pct=0;if(n.date>a.date)pct=100;else if(n.date<a.date)pct=0;else pct=Math.max(0,Math.min(100,(n.secs-startSec)/Math.max(1,endSec-startSec)*100));const q=s=>this.shadowRoot.querySelector(s),elapsed=q('.elapsed'),dot=q('.dot'),start=q('.actual-start'),end=q('.actual-end');if(elapsed)elapsed.style.width=pct+'%';if(dot)dot.style.left=pct+'%';const sp=(a.mins-displayStart)/(displayEnd-displayStart)*100,ep=(b.mins-displayStart)/(displayEnd-displayStart)*100;if(start)start.style.left=sp+'%';if(end)end.style.left=ep+'%';const t=this.shadowRoot.querySelectorAll('.times span');if(t.length===3){t[0].textContent=hhmm(displayStart);t[1].textContent=hhmm(Math.round((displayStart+displayEnd)/2));t[2].textContent=hhmm(displayEnd)}};
}
window.customCards=(window.customCards||[]).filter(c=>!['postnl-latest-mail-card','postnl-delivery-image-card'].includes(c.type));
console.info('%c POSTNL %c Lovelace patch v1.0.2 ','background:#FB6200;color:#fff;font-weight:700','background:#fff;color:#FB6200;font-weight:700');
