const BASE="/postnl_lrvdlinden_static",DOMAIN="postnl_lrvdlinden";
const ICON=`${BASE}/icon.svg`,VAN=`${BASE}/postnl-van.gif`,VAN_STATIC=`${BASE}/van-1.svg`;
const cache=new Map();
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const lang=h=>String(h?.language||navigator.language||"nl").toLowerCase().startsWith("nl")?"nl":"en";
const ent=(h,role,id)=>id&&h.states[id]?h.states[id]:Object.values(h.states).find(s=>s.attributes?.postnl_role===role);
const date=(v,l)=>{if(!v)return"—";const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat(l==="nl"?"nl-NL":"en-GB",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d)};
async function img(h,e,m){const k=`${e}:${m}`;if(!cache.has(k))cache.set(k,h.connection.sendMessagePromise({type:`${DOMAIN}/get_mail_image`,entry_id:e,mail_id:String(m)}).then(r=>{r=r?.result||r;return r?.content?`data:${r.content_type||"image/jpeg"};base64,${r.content}`:null}).catch(()=>null));return cache.get(k)}
const css=`:host{display:block}*{box-sizing:border-box}.c{overflow:hidden;border-radius:var(--ha-card-border-radius,17px);background:var(--card-background-color,#fff);color:var(--primary-text-color);box-shadow:var(--ha-card-box-shadow,0 2px 6px #0002);font:14px/1.3 system-ui,-apple-system,"Segoe UI",sans-serif}header{height:52px;display:flex;align-items:center;padding:0 17px;border-bottom:1px solid var(--divider-color,#ddd)}header img{width:36px;height:36px;object-fit:contain}header b{margin-left:auto;color:var(--secondary-text-color);font-size:18px}.empty{min-height:180px;display:grid;place-items:center;text-align:center;padding:24px;color:var(--secondary-text-color)}.orange{color:#fb6200}`;
class Base extends HTMLElement{constructor(){super();this.attachShadow({mode:"open"});this.cfg={}}setConfig(c){this.cfg=c||{}}set hass(h){this.h=h;this.render()}getCardSize(){return 6}static getStubConfig(){return{}}}
class Mail extends Base{async render(){if(!this.h)return;const l=lang(this.h),s=ent(this.h,"mail",this.cfg.entity),a=s?.attributes||{},it=a.items||[];this.shadowRoot.innerHTML=`<style>${css}.list{display:flex;gap:12px;padding:13px;overflow-x:auto}.m{flex:0 0 146px;cursor:pointer}.scan{height:132px;padding:7px;display:grid;place-items:center;border-radius:9px;background:color-mix(in srgb,var(--primary-text-color) 10%,transparent);overflow:hidden}.scan img{width:100%;height:100%;object-fit:contain;background:white;border-radius:4px}.d{text-align:center;margin:7px auto 0;padding:4px 10px;width:max-content;border-radius:20px;background:color-mix(in srgb,var(--primary-text-color) 12%,transparent);font-weight:800}.modal{display:none;position:fixed;inset:0;z-index:9999;background:#000c;place-items:center}.modal.on{display:grid}.modal img{max-width:94vw;max-height:90vh;background:#fff;border-radius:10px}</style><div class="c"><header><img src="${ICON}"><b>${l==="nl"?"Mijn Post":"My Mail"}</b></header>${it.length?`<div class="list">${it.map((x,i)=>`<div class="m" data-i="${i}"><div class="scan">✉</div><div class="d">${esc(date(x.delivery_date,l))}</div></div>`).join("")}</div>`:`<div class="empty">${l==="nl"?"Er wordt momenteel geen post verwacht.":"No mail is currently expected."}</div>`}<div class="modal"><img></div></div>`;const modal=this.shadowRoot.querySelector('.modal');modal.onclick=()=>modal.classList.remove('on');await Promise.all(it.map(async(x,i)=>{if(!x.image_available)return;const src=await img(this.h,a.entry_id,x.id),m=this.shadowRoot.querySelector(`.m[data-i="${i}"]`);if(src&&m){m.querySelector('.scan').innerHTML=`<img src="${src}">`;m.onclick=e=>{e.stopPropagation();modal.querySelector('img').src=src;modal.classList.add('on')}}}))}}
customElements.define("postnl-mail-card",Mail);
class Latest extends Base{async render(){if(!this.h)return;const l=lang(this.h),s=ent(this.h,"mail",this.cfg.entity),a=s?.attributes||{},x=(a.items||[])[0];this.shadowRoot.innerHTML=`<style>${css}.b{min-height:260px;padding:14px;display:grid;place-items:center}.b img{max-width:100%;max-height:430px;object-fit:contain;background:#fff;border-radius:8px}</style><div class="c"><header><img src="${ICON}"><b>${l==="nl"?"Laatste poststuk":"Latest mail item"}</b></header><div class="b">${x?"Afbeelding laden…":(l==="nl"?"Geen poststuk beschikbaar":"No mail item available")}</div></div>`;if(x?.image_available){const src=await img(this.h,a.entry_id,x.id);if(src)this.shadowRoot.querySelector('.b').innerHTML=`<img src="${src}">`}}}
customElements.define("postnl-latest-mail-card",Latest);
class Packages extends Base{render(){if(!this.h)return;const l=lang(this.h),s=ent(this.h,"packages",this.cfg.entity),it=(s?.attributes?.items||[]).slice(0,5);this.shadowRoot.innerHTML=`<style>${css}.list{padding:10px;display:grid;gap:8px}.p{display:grid;grid-template-columns:48px 1fr auto;gap:10px;align-items:center;padding:10px;border:1px solid var(--divider-color,#ddd);border-radius:12px;cursor:pointer}.p img{width:42px}.sender{font-weight:800}.small{font-size:11px;color:var(--secondary-text-color);overflow:hidden;text-overflow:ellipsis}.badge{font-size:10px;font-weight:800;color:#9a3f00;background:#fff0e6;padding:6px 8px;border-radius:20px}.modal{display:none;position:fixed;inset:0;z-index:9999;background:#000c;place-items:center}.modal.on{display:grid}.dlg{width:min(410px,94vw);max-height:86vh;overflow:auto;padding:22px;border-radius:22px;background:var(--card-background-color,#fff)}.grid{display:grid;grid-template-columns:120px 1fr;gap:9px;margin-top:18px}.k{color:var(--secondary-text-color)}</style><div class="c"><header><img src="${ICON}"><b>${l==="nl"?"Mijn Pakketten":"My Packages"}</b></header>${it.length?`<div class="list">${it.map((p,i)=>`<div class="p" data-i="${i}"><img src="${ICON}"><div><div class="sender">${esc(p.sender||"PostNL")}</div><div class="small">${esc(p.tracking||"")}</div><div class="small">${esc(p.delivery_window||date(p.delivery_date,l))}</div></div><span class="badge">${esc(p.status||"—")}</span></div>`).join("")}</div>`:`<div class="empty">${l==="nl"?"Er zijn geen pakketten onderweg.":"There are no parcels on the way."}</div>`}<div class="modal"><div class="dlg"></div></div></div>`;const mo=this.shadowRoot.querySelector('.modal'),d=this.shadowRoot.querySelector('.dlg');mo.onclick=e=>{if(e.target===mo)mo.classList.remove('on')};this.shadowRoot.querySelectorAll('.p').forEach(el=>el.onclick=()=>{const p=it[+el.dataset.i];d.innerHTML=`<h2>${esc(p.sender||"PostNL")}</h2><strong class="orange">${esc(p.status||"—")}</strong><div class="grid"><span class="k">Tracking</span><span>${esc(p.tracking||"—")}</span><span class="k">${l==="nl"?"Bezorgdatum":"Delivery date"}</span><span>${esc(date(p.delivery_date,l))}</span><span class="k">${l==="nl"?"Bezorgvenster":"Delivery window"}</span><span>${esc(p.delivery_window||"—")}</span><span class="k">${l==="nl"?"Laatste event":"Latest event"}</span><span>${esc(p.event||"—")}</span><span class="k">${l==="nl"?"Ontvanger":"Receiver"}</span><span>${esc(p.receiver||"—")}</span></div>`;mo.classList.add('on')}})}}
customElements.define("postnl-packages-card",Packages);
function deliveryHtml(p,l,square=false){if(!p)return `<div class="empty"><img style="max-width:260px" src="${VAN_STATIC}"><b>${l==="nl"?"Er is geen pakket onderweg":"There is no parcel on the way"}</b></div>`;return `<div class="delivery ${square?"square":""}"><div class="top"><img src="${ICON}"><div><strong>${esc(p.sender||"PostNL")}</strong><small>${esc(p.status||"")}</small></div></div><h2>${esc(p.delivery_window||date(p.delivery_date,l))}</h2><div class="van"><img src="${VAN}" onerror="this.src='${VAN_STATIC}'"></div>${p.tracking?`<div class="tracking">${esc(p.tracking)}</div>`:""}</div>`}
const deliveryCss=`${css}.delivery{padding:15px}.top{display:flex;gap:11px;align-items:center}.top>img{width:44px;height:44px}.top div{display:grid}.top small,.tracking{color:var(--secondary-text-color)}h2{font-size:16px;margin:15px 0 6px}.van{height:150px;display:grid;place-items:center;overflow:hidden}.van img{max-width:290px;max-height:145px;object-fit:contain}.tracking{text-align:center;font-size:11px}.square{aspect-ratio:1/1;display:flex;flex-direction:column;justify-content:center}.square .van{height:190px}.square .van img{max-width:78%;max-height:180px}`;
class Delivery extends Base{render(){if(!this.h)return;const l=lang(this.h),s=ent(this.h,"packages",this.cfg.entity),p=s?.attributes?.active_package;this.shadowRoot.innerHTML=`<style>${deliveryCss}</style><div class="c"><header><img src="${ICON}"><b>${l==="nl"?"Mijn Bezorging":"My Delivery"}</b></header>${deliveryHtml(p,l)}</div>`}}
customElements.define("postnl-delivery-card",Delivery);
class DeliveryImage extends Base{getCardSize(){return 8}render(){if(!this.h)return;const l=lang(this.h),s=ent(this.h,"packages",this.cfg.entity),p=s?.attributes?.active_package;this.shadowRoot.innerHTML=`<style>${deliveryCss}.c{aspect-ratio:1/1}</style><div class="c">${deliveryHtml(p,l,true)}</div>`}}
customElements.define("postnl-delivery-image-card",DeliveryImage);
window.customCards=window.customCards||[];
window.customCards.push(
{type:"postnl-mail-card",name:"PostNL – Mijn Post",description:"Poststukken inclusief scans",preview:true},
{type:"postnl-latest-mail-card",name:"PostNL – Laatste poststuk",description:"Laatste poststukscan",preview:true},
{type:"postnl-packages-card",name:"PostNL – Mijn Pakketten",description:"Pakketten met details",preview:true},
{type:"postnl-delivery-card",name:"PostNL – Mijn Bezorging",description:"Actuele bezorging",preview:true},
{type:"postnl-delivery-image-card",name:"PostNL – Mijn Bezorging image",description:"Vierkante bezorgweergave",preview:true});
console.info("%c POSTNL %c Lovelace cards v1.0.0 ","background:#fb6200;color:#fff;font-weight:700","background:#fff;color:#fb6200;font-weight:700");
